---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: discovery-apiserver-dev 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: discovery
      role: apiserver
      env: dev
  template: 
    metadata: 
      name: apiserver
      labels: 
        app: discovery
        role: apiserver
        env: dev
    spec: 
      containers: 
        - name: apiserver
          image: gcr.io/PROJECT_ID/discovery:BRANCH_NAME-SHORT_SHA
          ports: 
            - containerPort: 8080