---
 apiVersion: apps/v1
 kind: Deployment 
 metadata: 
   name: discovery 
   labels: 
     app: discovery
 spec: 
   replicas: 1
   selector: 
     matchLabels: 
       app: discovery 
   template: 
     metadata: 
       labels: 
         app: discovery
     spec: 
       containers: 
         - name: discovery
           image: davebhavinp/discovery:1.0.1
           ports: 
             - containerPort: 8080