server: 
   port: 8080 

eureka: 
  client: 
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl: 
      defaultZone: http://discovery-service:8080/eureka/
  instance: 
    preferIpAddress: true    

logging: 
  level: 
    root: INFO